[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["Mock721", "Mock1155", "MockHarvestContract", "MockMarketContract", "HarvestArtTest", "HarvestMarketTest"]