[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["Mock721", "Mock1155", "MockHarvestContract", "MockMarketContract", "HarvestTest", "MarketTest"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }